# https://github.com/coolsasindu/
# Don't Click This Link: https://bit.ly/3v8PLxm 

import time ,sys

def TextPrint(text):
	for cha in text:
		sys.stdout.write(cha)

# hacker
time.sleep(1.0)   
TextPrint("HECKER Today at 8:04 AM\n")
TextPrint("\ti know yor\n")
time.sleep(1.5)
TextPrint("\tpassword\n")
time.sleep(1.5) 
# me
TextPrint("g***ga Today at 8:05 AM\n")
TextPrint("\tno you dont\n")
time.sleep(1.5)

# hacker 
TextPrint("HECKER Today at 8:05 Am\n")
TextPrint("\tit's @@@###@@@\n")
time.sleep(1.5)

#me
TextPrint("g***ga Today at 8:05 AM\n")
TextPrint("\twait\n")
time.sleep(1.5)
TextPrint("\tWAIT\n")
time.sleep(1.5)
TextPrint("\thowd you get is ??\n")
time.sleep(1.5)
TextPrint("HECKER Today at 8:05 AM\n")
TextPrint("\ti hacked your wifi\n")
time.sleep(1.5)
TextPrint("\tthen your house\n")
time.sleep(1.5)
TextPrint("\tthen your computer\n")
time.sleep(1.5)
TextPrint("\tthen your webcam\n")
time.sleep(1.5)
TextPrint("g***ga Today at 8:06 AM\n")
TextPrint("\t~~~ ~!\n")
time.sleep(1.5)
TextPrint("HECKER Today at 8:06 AM\n")
TextPrint("\ti saw\n")
time.sleep(1.5)
TextPrint("\tthrough your camera\n")
time.sleep(1.5)
TextPrint("\tthe password\n")
time.sleep(1.5)
TextPrint("\twriten on a notepad\n")
time.sleep(1.5)
TextPrint("g***ga Today at 8:06 AM\n")
TextPrint("\tum\n")
time.sleep(1.5)
TextPrint("\tokay\n")
time.sleep(1.5)
TextPrint("\tthanks i guess ?\n")
time.sleep(1.5)
TextPrint("HECKER Today at 8:06 AM\n")
TextPrint("\thuh\n")
time.sleep(1.5)
TextPrint("g***ga Today at 8:06 AM\n")
TextPrint("\t i forgot my password\n")
time.sleep(1.5)
TextPrint("\t i so thanks (edited)\n")
time.sleep(1.5)
TextPrint("\t for telling me\n")
time.sleep(1.5)
TextPrint("\t pls\n")
time.sleep(.5)
TextPrint("\t pls\n")
time.sleep(.5)
TextPrint("\t plssssssss\n")
time.sleep(1.5)
TextPrint("HECKER Today at 8:06 AM\n")
TextPrint("\tdude.\n")
time.sleep(1.5)
TextPrint("\ti can log into \n")
time.sleep(1.5)
TextPrint("\tyourbank\n")
time.sleep(1.5)
TextPrint("g***ga Today at 8:06 AM\n")
TextPrint("\tmy bank was destroyed\n")
time.sleep(1.5)
TextPrint("\tin a flood\n")
time.sleep(1.5)
TextPrint("HECKER Today at 8:07 AM\n")
TextPrint("\ti will log into \n")
time.sleep(1.5)
TextPrint("\tyour paypal\n")
time.sleep(1.5)
TextPrint("g***ga Today at 8:07 AM\n")
TextPrint("\ti have no money \n")
time.sleep(1.5)
TextPrint("HECKER Today at 8:07 AM\n")
TextPrint("\tfine\n")
time.sleep(1.5)
TextPrint("\ti will read \n")
time.sleep(1.5)
TextPrint("\tyour private emails\n")
time.sleep(1.5)
TextPrint("g***ga Today at 8:07 AM\n")
TextPrint("\tok\n")
time.sleep(1.5)
TextPrint("\tgo ahead\n")
time.sleep(1.5)
TextPrint("HECKER Today at 8:07 AM\n")
TextPrint("\tyou think this is a joke ?\n")
time.sleep(1.5)
TextPrint("g***ga Today at 8:07 AM\n")
TextPrint("\tblushes\n")
time.sleep(1.5)
TextPrint("HECKER Today at 8:07 AM\n")
TextPrint("\tFINE\n")
time.sleep(1.5)
TextPrint("\ti will hack\n")
time.sleep(1.5)
TextPrint("\tyour facebook\n")
time.sleep(1.5)
TextPrint("\tand pretend to be you\n")
time.sleep(1.5)
TextPrint("g***ga Today at 8:07 AM\n")
TextPrint("\tbut~\n")
time.sleep(1.5)
TextPrint("\twhy be me\n")
time.sleep(1.5)
TextPrint("\twhen you can be\n")
time.sleep(1.5)
TextPrint("\tyourself\n")
time.sleep(1.5)
TextPrint("HECKER Today at 8:07 AM\n")
TextPrint("\tOMG\n")
time.sleep(1.5)
TextPrint("\tthats not the point\n")
time.sleep(1.5)
TextPrint("\tim a profesional hacker\n")
time.sleep(1.5)
TextPrint("g***ga Today at 8:07 AM\n")
TextPrint("\tOK\n")
time.sleep(1.5)
TextPrint("HECKER Today at 8:07 AM\n")
TextPrint("\twell\n")
time.sleep(1.5)
TextPrint("\tare you scared?\n")
time.sleep(1.5)
TextPrint("g***ga Today at 8:07 AM\n")
TextPrint("\tNo\n")
time.sleep(1.5)
TextPrint("\tNot really\n")
time.sleep(1.5)
TextPrint("HECKER Today at 8:07 AM\n")
TextPrint("\twhy NOT\n")
time.sleep(1.5)
TextPrint("g***ga Today at 8:07 AM\n")
TextPrint("\tBecause\n")
time.sleep(1.5)
TextPrint("\ti have nothing \n")
time.sleep(1.5)
TextPrint("\tto lose\n")
time.sleep(1.5)
TextPrint("\t:~~\n")
time.sleep(1.5)
TextPrint("HECKER Today at 8:07 AM\n")
TextPrint("\ti can find your IP\n")
time.sleep(1.5)
TextPrint("\ttrack it\n")
time.sleep(1.5)
TextPrint("\tand come to your house.\n")
time.sleep(1.5)
TextPrint("g***ga Today at 8:07 AM\n")
TextPrint("\tyess pls\n")
time.sleep(1.5)
TextPrint("\ti nedd friends\n")
time.sleep(1.5)
TextPrint("HECKER Today at 8:07 AM\n")
TextPrint("\ti am not your FRIEND\n")
time.sleep(1.5)
TextPrint("\ti am the ENEMY\n")
time.sleep(1.5)
TextPrint("g***ga Today at 8:07 AM\n")
TextPrint("\tI am A Girl\n")
time.sleep(1.5)
TextPrint("HECKER Today at 8:07 AM\n")
TextPrint("\tWhat\n")
time.sleep(1.5)
TextPrint("g***ga Today at 8:07 AM\n")
TextPrint("\tFind me\n")
time.sleep(1.5)
TextPrint("HECKER Today at 8:07 AM\n")
TextPrint("\tNo\n")
time.sleep(1.5)
TextPrint("\tNo way\n")
time.sleep(1.5)
TextPrint("\ti am Quite\n")
time.sleep(1.5)
